# Generated by Django 4.1.7 on 2023-03-12 05:36

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0005_transactionhistory"),
        ("sns", "0004_serverhistory"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "pub_key",
                    models.CharField(
                        help_text="public key",
                        max_length=100,
                        unique=True,
                        verbose_name="public key",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        help_text="secret key",
                        max_length=100,
                        verbose_name="secret key",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inboxes",
                        to="accounts.socialaccount",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inboxes",
                        to="blockchain.network",
                    ),
                ),
                (
                    "sns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inboxes",
                        to="sns.sns",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbox",
                "verbose_name_plural": "Inbox",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.AddConstraint(
            model_name="inbox",
            constraint=models.UniqueConstraint(
                fields=("pub_key", "network", "sns"),
                name="unique (pub_key, network, sns)",
            ),
        ),
    ]
