# Generated by Django 4.1.7 on 2023-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inbox_inbox_unique (pub_key, network, sns)'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='secret_key',
            field=models.CharField(help_text='secret key', max_length=400, verbose_name='secret key'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='secret_key',
            field=models.CharField(help_text='secret key', max_length=400, verbose_name='secret key'),
        ),
    ]
