# Generated by Django 4.1.7 on 2023-07-07 10:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_inbox_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='user Profile img', null=True, upload_to='social_user_profile_imgs', verbose_name='social user profile img'),
        ),
    ]
