# Generated by Django 4.1.7 on 2023-03-12 05:00

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0002_wallet_wallet_unique (network, address)"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Coin name (ex. Solana, USDCoin ...)",
                        max_length=50,
                        verbose_name="Coin name",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        help_text="Coin ticker (ex. SOL, USDC ...)",
                        max_length=10,
                        verbose_name="Coin ticker",
                    ),
                ),
                (
                    "symbol",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="coin symbol",
                        null=True,
                        upload_to="coin_symbol",
                        verbose_name="coin symbol",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to="blockchain.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin",
                "verbose_name_plural": "Coin",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.AddConstraint(
            model_name="coin",
            constraint=models.UniqueConstraint(
                fields=("network", "name"), name="unique (network, coin_name)"
            ),
        ),
    ]
