# Generated by Django 4.1.7 on 2023-03-12 05:08

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0003_coin_coin_unique (network, coin_name)"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="NFT name (ex. NOIS, Sodead ...)",
                        max_length=50,
                        verbose_name="NFT name",
                    ),
                ),
                (
                    "mint_address",
                    models.CharField(
                        blank=True,
                        help_text="mint address",
                        max_length=100,
                        null=True,
                        verbose_name="mint address",
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="nft thumbnail",
                        null=True,
                        upload_to="nft_thumbnail",
                        verbose_name="nft thumbnail",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_collections",
                        to="blockchain.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "NFT Collection",
                "verbose_name_plural": "NFT Collection",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("network", "name"), name="unique (network, nft_collection_name)"
            ),
        ),
    ]
