# Generated by Django 4.1.7 on 2023-03-12 05:16

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0004_serverhistory"),
        ("accounts", "0001_initial"),
        ("blockchain", "0004_collection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("COIN", "COIN TX"), ("NFT", "NFT TX")],
                        default="COIN",
                        help_text="TX type",
                        max_length=10,
                        verbose_name="TX type",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="tx hash",
                        max_length=100,
                        unique=True,
                        verbose_name="tx_hash",
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_tx",
                        to="accounts.socialaccount",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tx_histories",
                        to="sns.server",
                        unique=True,
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_tx",
                        to="accounts.socialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction History",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
    ]
