# Generated by Django 4.1.7 on 2023-06-29 04:31

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_remove_snsconnectioninfo_unique sns handle_and_more'),
        ('accounts', '0002_inbox_inbox_unique (pub_key, network, sns)'),
        ('blockchain', '0005_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='blockchain.coin', unique=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_coin_tx', to='accounts.socialaccount')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='sns.server', unique=True)),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_coin_tx', to='accounts.socialaccount')),
            ],
            options={
                'verbose_name': 'Coin Transaction History',
                'verbose_name_plural': 'Coin Transaction History',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='NFTTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='blockchain.collection', unique=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_nft_tx', to='accounts.socialaccount')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='sns.server', unique=True)),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_nft_tx', to='accounts.socialaccount')),
            ],
            options={
                'verbose_name': 'NFT Transaction History',
                'verbose_name_plural': 'NFT Transaction History',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
