# Generated by Django 4.1.7 on 2023-06-29 09:13

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_remove_snsconnectioninfo_unique sns handle_and_more'),
        ('accounts', '0003_alter_inbox_secret_key_and_more'),
        ('blockchain', '0005_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('amount', models.FloatField(default=0.0, help_text='sent coin amount', verbose_name='coin_amount')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='blockchain.coin')),
                ('from_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_coin_tx', to='accounts.inbox')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='sns.server')),
                ('to_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_coin_tx', to='accounts.inbox')),
            ],
            options={
                'verbose_name': 'Coin Transaction History',
                'verbose_name_plural': 'Coin Transaction History',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(help_text='NFT name (ex. NOIS #100, ...)', max_length=50, verbose_name='NFT name')),
                ('mint_address', models.CharField(blank=True, help_text='mint address', max_length=100, null=True, verbose_name='mint address')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='nft image', null=True, upload_to='nft_image', verbose_name='NFT Image')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='blockchain.collection')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='blockchain.network')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTs',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='NFTTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('from_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_nft_tx', to='accounts.inbox')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='blockchain.nft')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='sns.server')),
                ('to_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_nft_tx', to='accounts.inbox')),
            ],
            options={
                'verbose_name': 'NFT Transaction History',
                'verbose_name_plural': 'NFT Transaction History',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.AddConstraint(
            model_name='nft',
            constraint=models.UniqueConstraint(fields=('network', 'name'), name='unique (network, nft_name)'),
        ),
    ]
