# Generated by Django 4.1.7 on 2023-06-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_cointransactionhistory_nft_nfttransactionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='mint_address',
            field=models.CharField(blank=True, help_text='mint address', max_length=100, null=True, verbose_name='mint address'),
        ),
    ]
