# Generated by Django 4.1.7 on 2023-06-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_remove_snsconnectioninfo_unique sns handle_and_more'),
        ('blockchain', '0006_cointransactionhistory_nfttransactionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransactionhistory',
            name='amount',
            field=models.FloatField(default=0.0, help_text='sent coin amount', verbose_name='coin_amount'),
        ),
        migrations.AlterField(
            model_name='cointransactionhistory',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='blockchain.coin'),
        ),
        migrations.AlterField(
            model_name='cointransactionhistory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='sns.server'),
        ),
        migrations.AlterField(
            model_name='nfttransactionhistory',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='blockchain.collection'),
        ),
        migrations.AlterField(
            model_name='nfttransactionhistory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='sns.server'),
        ),
    ]
