# Generated by Django 4.1.7 on 2023-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_coin_mint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransactionhistory',
            name='amount',
            field=models.CharField(default='0', help_text='sent coin amount', max_length=100, verbose_name='coin_amount'),
        ),
    ]
