# Generated by Django 4.1.7 on 2023-07-08 03:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_coin_mint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='nft thumbnail', null=True, upload_to='nft_thumbnail', verbose_name='nft thumbnail'),
        ),
        migrations.AlterField(
            model_name='cointransactionhistory',
            name='amount',
            field=models.CharField(default='0', help_text='sent coin amount', max_length=100, verbose_name='coin_amount'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='nft collection thumbnail', null=True, upload_to='nft_collection_thumbnail', verbose_name='nft collection thumbnail'),
        ),
    ]
