# Generated by Django 4.1.7 on 2023-07-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_nft_thumbnail_alter_cointransactionhistory_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='thumbnail',
        ),
    ]
