# Generated by Django 4.2.3 on 2023-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_socialaccount_profile_img'),
        ('blockchain', '0009_remove_nft_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, help_text='Coin name (ex. Solana, USDCoin ...)', max_length=50, verbose_name='Coin name'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(blank=True, help_text='Coin ticker (ex. SOL, USDC ...)', max_length=10, verbose_name='Coin ticker'),
        ),
        migrations.CreateModel(
            name='WalletTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('wallet_address', models.CharField(help_text='wallet address', max_length=100, verbose_name='wallet_address')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('register_type', models.CharField(choices=[('REGISTER', 'REGISTER'), ('UNREGISTER', 'UNREGISTER')], help_text='Register type', max_length=10, verbose_name='register_type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction_history', to='accounts.socialaccount')),
            ],
            options={
                'verbose_name': 'Wallet Transaction History',
                'verbose_name_plural': 'Wallet Transaction History',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
    ]
