# Generated by Django 4.1.7 on 2023-03-12 03:23

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0002_snsconnectioninfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="SNS server name (ex. ATIV, NOIS, ...)",
                        max_length=50,
                        verbose_name="SNS server name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server",
                "verbose_name_plural": "Server",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.AddConstraint(
            model_name="snsconnectioninfo",
            constraint=models.UniqueConstraint(
                fields=("sns", "handle"), name="unique sns handle"
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="sns",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servers",
                to="sns.sns",
            ),
        ),
        migrations.AddConstraint(
            model_name="server",
            constraint=models.UniqueConstraint(
                fields=("sns", "name"), name="unique (sns, server)"
            ),
        ),
    ]
