# Generated by Django 4.1.7 on 2023-03-12 03:32

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0003_server_snsconnectioninfo_unique sns handle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at model"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user creates model",
                        null=True,
                        verbose_name="user creates model",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at model"
                    ),
                ),
                (
                    "updated_by",
                    models.IntegerField(
                        blank=True,
                        help_text="user updates model",
                        null=True,
                        verbose_name="user updates model",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="just flag, not delete data actually",
                        verbose_name="Whether model is deleted",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date stored history"
                    ),
                ),
                (
                    "member_count",
                    models.IntegerField(null=True, verbose_name="# of server members"),
                ),
                (
                    "daily_chat_count",
                    models.IntegerField(null=True, verbose_name="# of chats in server"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="histories",
                        to="sns.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server History",
                "verbose_name_plural": "Server History",
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
    ]
