# Generated by Django 4.1.7 on 2023-06-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_serverhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsconnectioninfo',
            name='discriminator',
            field=models.CharField(blank=True, help_text='SNS discriminator', max_length=100, null=True, verbose_name='SNS discriminator'),
        ),
    ]
