# Generated by Django 4.1.7 on 2023-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_snsconnectioninfo_discriminator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='snsconnectioninfo',
            name='unique sns handle',
        ),
        migrations.AlterField(
            model_name='snsconnectioninfo',
            name='discriminator',
            field=models.CharField(help_text='SNS discriminator', max_length=100, verbose_name='SNS discriminator'),
        ),
        migrations.AddConstraint(
            model_name='snsconnectioninfo',
            constraint=models.UniqueConstraint(fields=('sns', 'handle', 'discriminator'), name='unique sns handle'),
        ),
    ]
