# Generated by Django 4.1.7 on 2023-07-07 10:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_remove_snsconnectioninfo_unique sns handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsconnectioninfo',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='user Profile img', null=True, upload_to='sns_user_profile_imgs', verbose_name='sns user profile img'),
        ),
    ]
